# Generated by Django 5.2 on 2025-05-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trace",
            name="params",
        ),
    ]
