# Generated by Django 4.2.21 on 2025-06-13 11:55

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authentication",
            name="authorization_code",
            field=django_cryptography.fields.encrypt(
                models.CharField(
                    blank=True,
                    default=None,
                    help_text="The code received from OAuth2 provider to exchange for access token.",
                    max_length=255,
                    null=True,
                    verbose_name="authorization code",
                )
            ),
        ),
        migrations.AddField(
            model_name="authentication",
            name="redirect_uri",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="One of the OAuth2 redirect URIs listed for the given client_id.",
                null=True,
                verbose_name="redirect URI",
            ),
        ),
        migrations.AddField(
            model_name="authentication",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="The OAuth2 state to maintain state between authorization request and callback.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="state",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="auth_url",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="The URL to be used to get the user authorization code.",
                null=True,
                verbose_name="authorization URL",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="documentation_url",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="The URL of the API documentation.",
                null=True,
                verbose_name="documentation URL",
            ),
        ),
        migrations.AddField(
            model_name="trace",
            name="response",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The parsed response based on the expected content type.",
                null=True,
                verbose_name="response",
            ),
        ),
        migrations.AddField(
            model_name="trace",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1xx", "Informational"),
                    ("2xx", "Success"),
                    ("3xx", "Redirect"),
                    ("4xx", "Client Error"),
                    ("5xx", "Server Error"),
                ],
                default=None,
                help_text="The status of the request response.",
                max_length=3,
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="authentication",
            name="access_token",
            field=django_cryptography.fields.encrypt(
                models.CharField(
                    blank=True,
                    default=None,
                    help_text="The access token to be used for authentication.",
                    max_length=512,
                    null=True,
                    verbose_name="access token",
                )
            ),
        ),
        migrations.AlterField(
            model_name="authentication",
            name="email",
            field=models.CharField(help_text="The user email.", max_length=255, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="authentication",
            name="refresh_token",
            field=django_cryptography.fields.encrypt(
                models.CharField(
                    blank=True,
                    default=None,
                    help_text="The refresh token to be used for refreshing the access token.",
                    max_length=512,
                    null=True,
                    verbose_name="refresh token",
                )
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="auth_flow",
            field=models.CharField(
                blank=True,
                choices=[
                    ("api_key", "API key"),
                    ("basic_authentication", "Basic authentication"),
                    ("authorization_code", "Authorization code"),
                    ("client_credentials", "Client credentials"),
                ],
                default=None,
                help_text="Tells how to authenticate against the service. If not set, no authentication will be used.",
                max_length=255,
                null=True,
                verbose_name="authenfication flow",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="token_url",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="The URL to be used to request or refresh the user token.",
                null=True,
                verbose_name="token URL",
            ),
        ),
    ]
