# Generated by Django 4.2.21 on 2025-06-07 11:44

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0002_authentication_authorization_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authentication",
            name="authorization_code",
            field=django_cryptography.fields.encrypt(
                models.CharField(
                    blank=True,
                    default=None,
                    help_text="The code received from OAuth2 provider to exchange for access token.",
                    max_length=255,
                    null=True,
                    verbose_name="authorization code",
                )
            ),
        ),
    ]
