# Generated by Django 5.2.1 on 2025-05-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0002_remove_trace_params"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="method",
            field=models.CharField(
                choices=[("get", "GET"), ("post", "POST"), ("put", "PUT"), ("patch", "PATCH"), ("delete", "DELETE")],
                help_text="The HTTP method used to request the endpoint with.",
                max_length=10,
                verbose_name="method",
            ),
        ),
        migrations.AlterField(
            model_name="trace",
            name="method",
            field=models.CharField(
                choices=[("get", "GET"), ("post", "POST"), ("put", "PUT"), ("patch", "PATCH"), ("delete", "DELETE")],
                help_text="The HTTP method used to request the endpoint with.",
                max_length=10,
                verbose_name="method",
            ),
        ),
    ]
