# Generated by Django 4.2.21 on 2025-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0003_alter_authentication_authorization_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="authentication",
            name="redirect_uri",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="One of the OAuth2 redirect URIs listed for the given client_id.",
                null=True,
                verbose_name="redirect URI",
            ),
        ),
    ]
