# Generated by Django 4.2.21 on 2025-06-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0004_authentication_redirect_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="documentation_url",
            field=models.URLField(
                blank=True,
                default=None,
                help_text="The URL of the API documentation.",
                null=True,
                verbose_name="documentation URL",
            ),
        ),
    ]
